# Generated by Django 5.1 on 2024-12-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_classroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Taken', 'Taken')], max_length=10, null=True),
        ),
    ]
