# Generated by Django 5.1 on 2024-12-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_classroom_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='status',
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
