# Generated by Django 5.1 on 2025-02-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_request_reason_for_disapproval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='reason_for_disapproval',
        ),
        migrations.AlterField(
            model_name='request',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(max_length=255),
        ),
    ]
