# Generated by Django 5.1 on 2025-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_classroom_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='facility_type',
            field=models.CharField(max_length=255),
        ),
    ]
