# Generated by Django 5.1 on 2025-02-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_classroom_facility_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='updated_at',
        ),
    ]
