# Generated by Django 5.1 on 2025-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_classroom_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='alloted_slots',
            field=models.IntegerField(default=1),
        ),
    ]
